version: "2"
services:
  php-fpm:
    image: dockerkit/php-fpm:7.0.12-gd-imagick
    volumes:
     - ./src:/srv/web
     - node_modules:/srv/web/node_modules
    working_dir: /srv/web
    hostname: docker-php-fpm
    ports:
     - "9001:9000"
    user: ""
    links:
     - database
  nginx:
    image: nginx:1.10.1-alpine
    volumes: 
     - ./src:/srv/web
     - ./config/docker/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - "81:80"
    links:
     - php-fpm:fcgi
  database:
    image: postgres:9.5.2
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=db_blog
    expose:
     - "5432"
    ports:
     - "5433:5432"
volumes:
    node_modules: {}